# Generated by Django 3.0.4 on 2020-10-08 07:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='user image/%Y/%m/%d/', verbose_name='User Image')),
                ('user_name', models.CharField(max_length=200)),
                ('user_profession', models.CharField(max_length=500)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_address', models.CharField(max_length=500)),
                ('facebook_link', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsup_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('github_link', models.CharField(blank=True, max_length=200, null=True)),
                ('stackoverflow_link', models.CharField(blank=True, max_length=200, null=True)),
                ('user_info', models.TextField(verbose_name='About Me')),
                ('user_experience', models.TextField(verbose_name='Experience')),
                ('user_edu', models.TextField(verbose_name='Education And Training')),
            ],
        ),
    ]
